export const colors = {
    normal: 'black',
    selected: 'rgb(225,0,0)',
    unselected: 'rgba(0,225,204,1)',
    double: 'rgb(120,0,225)',
    tags_colors : [
        'DarkGoldenRod',
        'Orange',
        'blue',
        'Olive',
        'SkyBlue',
        'SeaGreen',
        'Yellow',
        'Green',
        'GoldenRod',
        'OrangeRed',
        'NavajoWhite',
        'Lime',
        'Pink',
        'DarkSlateGrey',
        'HotPink',
        'DarkKhaki',
        'Tan',
        'Peru',
        'PaleGreen',
        'MediumBlue',
        'DarkRed',
        'LightSlateGrey',
    ]
}
